// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCToD3jN4hlF_9EdaJ5pUGFffn6E2tloCg',
    appId: '1:688888385423:web:81f12fc77fbc7107c2c5fa',
    messagingSenderId: '688888385423',
    projectId: 'epresensi-d63f0',
    authDomain: 'epresensi-d63f0.firebaseapp.com',
    storageBucket: 'epresensi-d63f0.firebasestorage.app',
    measurementId: 'G-R426LZCHMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9khPV4CKvbxiuUGAucSA4KRDn4495Dw',
    appId: '1:688888385423:android:5f68c977b97db845c2c5fa',
    messagingSenderId: '688888385423',
    projectId: 'epresensi-d63f0',
    storageBucket: 'epresensi-d63f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4EFMZDyh-3EWpQmgAYL4MnoN4BFo6cI',
    appId: '1:688888385423:ios:6ec58ca82fb1bfc2c2c5fa',
    messagingSenderId: '688888385423',
    projectId: 'epresensi-d63f0',
    storageBucket: 'epresensi-d63f0.firebasestorage.app',
    iosBundleId: 'com.ePresensi.ePresensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4EFMZDyh-3EWpQmgAYL4MnoN4BFo6cI',
    appId: '1:688888385423:ios:6ec58ca82fb1bfc2c2c5fa',
    messagingSenderId: '688888385423',
    projectId: 'epresensi-d63f0',
    storageBucket: 'epresensi-d63f0.firebasestorage.app',
    iosBundleId: 'com.ePresensi.ePresensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCToD3jN4hlF_9EdaJ5pUGFffn6E2tloCg',
    appId: '1:688888385423:web:dfbb8bbaedc5805cc2c5fa',
    messagingSenderId: '688888385423',
    projectId: 'epresensi-d63f0',
    authDomain: 'epresensi-d63f0.firebaseapp.com',
    storageBucket: 'epresensi-d63f0.firebasestorage.app',
    measurementId: 'G-8SY7KNJTDK',
  );
}
